R/plot.R
R/symbolic_units.R
tests/testthat/test_arith.R
tests/testthat/test_symbolic_units.R

This PR just changes the way units are printed when they are translated into characters. Instead of being shown as sequences of multiplication, such as `m*m*m`, they are shown as powers, `m^3`.

Pretty print expressions so sequences of multiplications are shown as powers

---

R/summaries.R

This is a very straightforward change that doesn't affect `units` at all (the behaviour is exactly the same), but enables integration into `quantities`. If `units` (or `errors`) calls `print` and `format` directly, there's nothing (reasonable) I can do from `quantities` to integrate the output.

use NextMethod for formatting and printing

---

R/misc.R

As in #107, this change doesn't affect `units` behaviour, but enables integration into `quantities`.

use NextMethod for concatenation

---

R/misc.R
R/summaries.R

The previous patch apparently worked, at least for `units` alone, but effectively `NextMethod` wasn't dispatching any method after `c.units`. I still don't understand why, and it may be a bug in R, because the same code has a different behaviour depending on the scope (i.e., whether the methods are defined in the global environment or exported from packages; see [this reprex](https://github.com/Enchufa2/dispatchS3dots) for more details).
However, I managed to circumvent this issue with this patch. It's based on calling `c` once more if any argument was modified (units changed), and finally calling `NextMethod` cleanly. It is not an ideal solution, because this means that, if any unit changes, `c.units` is called _twice_. But AFAIK, it may be the only solution. And if there is a bug in R, …

use NextMethod for concatenation (2)

---

R/plot.R

- No need to `unclass` in `plot`.
- `NextMethod` usage was wrong (call not modified).

fixes for plot and hist

---

R/math.R
tests/testthat/test_math.R

It was previously reporting "not meaningful for units", regardless of the units.

fix sqrt to behave as ^0.5

---

R/math.R
tests/testthat/test_math.R

Simple patch that returns ASAP. 
Under this _principle_, this whole `Math.units` can be improved in terms of performance (the same applies to `Ops.units`). I've been tempted, but I love, as you said once, _fancy things_, such as [this](https://github.com/r-quantities/errors/blob/master/R/math.R#L26), and you may not like it. So I leave the _greater good_ for another day, another discussion. :-)

fix #115: sign drops units

---

R/init.R
R/make_units.R
R/valid_udunits.R
tests/testthat/test_conversion.R
tests/testthat/test_unit_creation.R

With this implementation, the symbolic units are preserved so they can be printed correctly, and assigning a unit like "mg/kg" no longer changes the numeric value of the target vector.
Also, fixes the regression mentioned here (and elsewhere):
https://github.com/r-quantities/units/pull/64#issuecomment-339036324

alternative solution to #89; #91

---

R/arith.R

- Only `+` and `-` can be unary, so the check was redundant.
- Unary `+` and `-` don't drop classes or attributes, so it is safe and enough to return `NextMethod()`.

use NextMethod for unary ops

---

R/conversion.R
R/set_units.R
tests/testthat/test_conversion.R

To be able to implement all combinations of units/errors setting/dropping for `quantities`, `set_units` must delegate to `units<-`. And for that, `as_units(NULL)` must return `NULL`, which would be expected I'd say.

unit dropping consistency

---

R/plot.R

Sorry for this, I was **completely wrong** about this. I said that the call was not being modified, so it was not necessary to provide the labs, but **of course it is** being modified! The user types `plot(something)` and the method **adds** the labels... I should have checked it more carefully.

fix plot and hist (2)

---

R/arith.R
R/symbolic_units.R

I've just realised that @mailund's PR broke `NextMethod` dispatch by calling `as.numeric(NextMethod())`. In `quantities`, units methods are always called in the first place, because if the operation needs a unit conversion, errors for that conversion must be propagated. Thus, enclosing `NextMethod` in `as.numeric` throws the errors out.
In the same way, we cannot rely on conversions using the C API (i.e., calling `convert`) directly, because errors are not propagated either. All conversions must ~take place at R level~ be wrapped inside a registered method (i.e., `units<-`), to be able to intercept the call and retrieve the conversion applied from `quantities`. See changes in `.simplify_units` for further details.

fix multiplication and division (2)

---

.Rbuildignore
.travis.yml

I've created a script ([here](https://github.com/r-quantities/quantities/blob/master/scripts/check_with_quantities.sh)) to be used by `units` and `errors` (already deployed there) on Travis CI. The idea is to early detect breaking changes, which can be otherwise difficult to solve due to the tight integration of `quantities` with both packages. It builds and checks the package (Travis' default behaviour), and after that, it checks `quantities` too. I've added log folding too for convenience, as Travis does (see [the log](https://travis-ci.org/r-quantities/units/jobs/395518735)).
These minimal changes are needed to use it, as can be seen in the diff:
- Install a Github-fresh copy of the other package (`errors` for `units` and viceversa).
- Clone the `quantities` repo.
- Launch the script. …

revdep quantities

---

configure.ac

AC_CHECK_HEADER was not using the specified --with-udunits2-include argument or the UDUNITS2_INCLUDE environment variable.
The CPPFLAGS were never updated, and the UD_CPPFLAGS never used in AC_CHECK_HEADER. This fixes the situation.

use specified udunits header locations

---

DESCRIPTION

The template argument missing in #168 was added [in release 0.12.10](https://github.com/RcppCore/Rcpp/commit/e3799de10288b0bbbdb663ec2b8f5073f4542889#diff-02f0b547c2779d25cff89672135f20e3).

close #168: set minimum Rcpp version required

---

DESCRIPTION
NEWS.md
R/conversion.R
R/make_units.R
R/misc.R
R/options.R
R/symbolic_units.R
R/valid_udunits.R
man/as_units.Rd
man/deparse_unit.Rd
man/hist.units.Rd
man/install_conversion_constant.Rd
man/mixed_units.Rd
man/plot.units.Rd
man/tibble.Rd
man/units.Rd
man/units_options.Rd
man/valid_udunits.Rd
tests/testthat/test_conversion.R
tests/testthat/test_misc.R
tests/testthat/test_mixed.R
vignettes/measurement_units_in_R.Rmd

Suggested packages were not properly guarded in examples, vignettes and tests, and `R CMD check` was failing if those suggests were not installed.
This PR includes commits from `convert_to_base`, which needs to be merged in `master`.

Guard suggests usage in examples, vignettes and tests

---

.travis.yml
NEWS.md
R/init.R
src/io.c
src/io.h
src/udunits.cpp
src/units.h
tests/plot.R
tests/testthat.R
tests/testthat/test_conversion.R
tests/testthat/test_misc.R
tests/testthat/test_mixed.R
tests/testthat/test_udunits.R
tests/testthat/test_user_conversion.R

- Avoid loading/unloading the package during tests ([that's a problem](http://r.789695.n4.nabble.com/SIGSEGV-in-R-RunWeakRefFinalizer-object-allocated-with-Rcpp-td4751510.html)) to fix valgrind issues. Otherwise, some weak ref finalizers may run after the unit system has been freed.
- Tidy up tests to ensure that options and units are restored.

close #192: fix valgrind issues

---

.travis.yml
R/RcppExports.R
R/init.R
R/user_conversion.R
src/RcppExports.cpp
src/udunits.cpp

[This](https://github.com/r-quantities/units/compare/unload?expand=1#diff-2711d8988b4edf6562a0668d7e873c13R27) trick is not very elegant, but it's actually needed. The thing is, each time a unit is wrapped into an Rcpp XPtr, a weak finalizer is registered (which calls to `ut_free` eventually). This is a problem, because we can't control when they are executed. As a result, the package cannot be unloaded cleanly, because there's [a segfault](https://travis-ci.org/r-quantities/units/jobs/504166374#L1376) (builds succeeded because we hadn't [warnings_are_errors](https://github.com/r-quantities/units/compare/unload?expand=1#diff-354f30a63fb0907d4ad57269548329e3R9) set). The segfault happened because 1) `ut_free_system` was called upon unloading, and then 2) `ut_free` was called randomly in a …

Force units' finalizers before freeing the system

---

DESCRIPTION
README.md
inst/CITATION
vignettes/measurement_units_in_R.bib
vignettes/measurement_units_in_R.html

Now R Journal publications [have a DOI](https://journal.r-project.org/archive/2016/RJ-2016-061/index.html)! Changes here:
- DOI added to DESCRIPTION
- Reference updated in README + minor rewriting
- Reference updated in CITATION + update to newer method `bibentry`
- Reference updated in `.bib` and `.html` under `vignettes`

update R Journal citation

---

NEWS.md
R/deprecated.R
R/make_units.R
R/user_conversion.R
tests/testthat/test_user_conversion.R

Current checks:
- Leading and trailing numbers.
- Arithmetic operators.
- Intermediate white spaces.
Am I missing something?

Fix #208: validate units before installation

---

DESCRIPTION
NAMESPACE
NEWS.md
R/misc.R
man/ud_units.Rd
man/unitless.Rd
tests/testthat/test_misc.R

With this patch,
```r
x <- set_units(24, h)
x[2] <- set_units(1440, min)
x
#> Units: [h]
#> [1] 24 24
x[2] <- set_units(3, m)
#> Error: cannot convert m into h
h <- data.frame(dt = set_units(24, "h"))
min <- data.frame(dt = set_units(1440, "min"))
rbind(h, min)
#>       dt
#> 1 24 [h]
#> 2 24 [h]
rbind(min, h)
#>           dt
#> 1 1440 [min]
#> 2 1440 [min]
```

close #232: fix replacement of parts of units

---

tests/testthat/_snaps/misc.md
tests/testthat/test_misc.R

possible because we now have testthat >= 3.0.0 .

Use snapshot test for str()

---

R/conversion.R
R/make_units.R
tests/testthat/test_misc.R

This would be easier and faster if vctrs was an imported package, because we could then use `vec_restore()`.
Do you see strong reasons against importing vctrs? We don't necessarily need to change the class hierarchy, although by inheriting from `"vctrs_vctr"` a lot of code here would be obsolete or could be changed.

[ and [[ keep attributes

---

.github/workflows/quantities.yml
R/make_units.R
R/tidyverse.R

Required for `vec_slice()`. Follow-up to #275.

Keep pillar attribute in vec_restore()

---

NEWS.md
R/conversion.R
man/units.Rd
src/udunits.cpp
tests/testthat/test_conversion.R

Fix #305
Now, names are preserved with unit conversion.  The underlying issue is that the C-connection function `ud_convert` drops the names.  I don't know how to fix that, and it seems to be used only at the location that I found in the code.

Preserve names with unit conversion

---

NEWS.md
R/arith.R
tests/testthat/test_arith.R

Fix #310
This always allows division of units, if they are equal, and it returns a unitless object.

Always allow division of identical units

---

R/arith.R
tests/testthat/test_arith.R

Fix #364.
I have enhanced tests for `%%` to make sure it behaves correctly.

Use `floor()` instead of `round()` in `%%`

---

R/helpers.R
man/keep_units.Rd
tests/testthat/test_helpers.R

add passthrough for `keep_units()` when units are not provided

---

NEWS.md
R/arith.R
R/conversion.R
R/math.R

Replaces some more calls to `as.character.symbolic_units` where just `ud_char` is enough.

Several performance improvements (4)

---

DESCRIPTION
NEWS.md
R/udunits.R
man/udunits2.Rd
tests/testthat/test_udunits.R

Closes #404 
@pepijn-devries Is this what you need?

vectorize ud_* helpers
